//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_SHOP.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        public int Номер_Заказа { get; set; }
        public int Код_сотрудника { get; set; }
        public int Код_товара { get; set; }
        public int ID_Клиента { get; set; }
        public System.DateTime Дата_оформления { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Товары Товары { get; set; }
    }
}
